export const products = [
    {
      id: 1,
      name: "iPhone 15",
      category: "Electronics",
      price: 69999,
      rating: 4.8,
      image: "https://picsum.photos/300/200?random=1",
    },
    {
      id: 2,
      name: "MacBook Air M2",
      category: "Electronics",
      price: 89999,
      rating: 4.9,
      image: "https://picsum.photos/300/200?random=2",
    },
    {
      id: 3,
      name: "React Book",
      category: "Books",
      price: 899,
      rating: 4.5,
      image: "https://picsum.photos/300/200?random=3",
    },
    {
      id: 4,
      name: "JavaScript Guide",
      category: "Books",
      price: 699,
      rating: 4.7,
      image: "https://picsum.photos/300/200?random=4",
    },
    {
      id: 5,
      name: "T-Shirt",
      category: "Clothing",
      price: 799,
      rating: 4.2,
      image: "https://picsum.photos/300/200?random=5",
    },
    {
      id: 6,
      name: "Running Shoes",
      category: "Clothing",
      price: 2499,
      rating: 4.6,
      image: "https://picsum.photos/300/200?random=6",
    },
    {
      id: 7,
      name: "Organic Rice",
      category: "Grocery",
      price: 599,
      rating: 4.4,
      image: "https://picsum.photos/300/200?random=7",
    },
    {
      id: 8,
      name: "Coffee Beans",
      category: "Grocery",
      price: 899,
      rating: 4.3,
      image: "https://picsum.photos/300/200?random=8",
    },
  ];